adding the translator experimental with Keras
crisywini/xalaxians-ai pull request #5
Opened 2023-09-21 13:44 UTC by manimotion

# Changes 🤖

- Added the File with the translator experimental with Keras
- Added the libraries in the Requirements file.

# Modified Data folders?  📚
- [ ] external
- [ ] interim
- [ ] processed
- [ ] raw

# Created new notebooks? 🐉
- [x] Yes
- [ ] No

# Created new reports? 📜
- [ ] Yes
- [x] No

# Created new models? 🐶
- [x] Yes
- [] No

# Do you feel happy with the changes? 🦥
- [x] Yes
- [ ] No

2023-09-21 14:53 UTC, crisywini commented on requirements.txt
> +conda install -c anaconda scipy}
fix this please

2023-09-21 14:53 UTC, crisywini requested changes
Check the requirements

2023-09-21 15:50 UTC, manimotion commented on requirements.txt
> +conda install -c anaconda scipy}
Fixed!

2023-09-22 13:44 UTC, crisywini approved these changes
Perfect! just update your changes with develop

2023-09-22 16:20 UTC, merged